version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo $(aws ecr get-login-password --region $AWS_DEFAULT_REGION) | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - REPOSITORY_URI=$ECR_REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Build completed on `date`
      - aws cloudformation package --template-file template.yml --s3-bucket $S3_BUCKET_NAME --output-template-file packaged-template.yml
      - |
        CHANGE_SET=$(aws cloudformation create-change-set --template-body file://packaged-template.yml --stack-name $STACK_NAME --change-set-name changeset-$(date +%s) --capabilities CAPABILITY_NAMED_IAM --parameters ParameterKey=ECRImageURI,ParameterValue=$ECR_REPOSITORY_URI:latest)
        CHANGE_SET_STATUS=$(echo $CHANGE_SET | jq -r .Status)
        if [ "$CHANGE_SET_STATUS" != "FAILED" ]; then
          aws cloudformation execute-change-set --change-set-name $(echo $CHANGE_SET | jq -r .Id)
        else
          echo "No changes to deploy."
        fi
